rules:
- id: find-safe-ui-violation-handling
  message: |
    Finding Safe Violation Handling
  metadata:
    type: Safe UI Violation Handling by WeakPtr
  severity: ERROR
  patterns:
    - pattern-either: 
      - pattern: |
          $FREE_FUNC(...);
          if (!$WEAK_VAR)
            return ...;
      - pattern: |
          $FREE_FUNC(...);
          if ($WEAK_VAR) {
            ...
          }
      - pattern: |
          $FREE_FUNC(...);
          if (!$WEAK_VAR || ...)
            return ...;
      - pattern: |
          $FREE_FUNC(...);
          if ($WEAK_VAR && ...) {
            ...
          }
      - pattern: |
          $ANOTHER_FUNC($FREE_FUNC(...));
          if (!$WEAK_VAR || ...)
            return ...;
      - pattern: |
          $ANOTHER_FUNC($FREE_FUNC(...));
          if (!$WEAK_VAR)
            return ...;
    - metavariable-regex:
        metavariable: $WEAK_VAR
        regex: (^observed_[a-z]+$) 
    - focus-metavariable: $FREE_FUNC
  languages:
  - c++
